#!/bin/bash

tar cvf payload.tar bin/ng-i686 bin/ng-x86_64 clin.jar
for i in `ls lib/*.jar`; do
    tar -vrf payload.tar $i
done

if [ -e "payload.tar" ]; then
    gzip payload.tar

    if [ -e "payload.tar.gz" ]; then
        cat bin/clin payload.tar.gz > clin
        rm payload.tar.gz
    else
        echo "payload.tar.gz does not exist"
        exit 1
    fi
else
    echo "payload.tar does not exist"
    exit 1
fi

chmod +x clin
echo "clin self extracting script created"
exit 0
