#!/bin/bash


javac src/jark/util/SystemThreadList.java  -d classes/ &> /dev/null
if [ $? != 0 ]; then 
    echo "javac not installed, exiting"
    exit 1
fi
lein jar

touch jark-deps.txt
:> jark-deps.txt
for i in `ls lib/*.jar`; do
    echo $i >> jark-deps.txt
done

tar cvf payload.tar bin/ng-i686 bin/ng-x86_64 *.jar jark-deps.txt modules/

for i in `ls lib/*.jar`; do
    tar -vrf payload.tar $i
done

if [ -e "payload.tar" ]; then
    gzip payload.tar

    if [ -e "payload.tar.gz" ]; then
        cat bin/jark.bin payload.tar.gz > jark
        rm payload.tar.gz
    else
        echo "payload.tar.gz does not exist"
        exit 1
    fi
else
    echo "payload.tar does not exist"
    exit 1
fi

chmod +x jark
echo "jark self extracting script created"
exit 0
